In [1]:
import numpy as np

# numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [6]:
np.array(benimListem)

array([20, 30, 40])

In [7]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [8]:
matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros&ones

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# linspace

In [19]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# eye

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [24]:
np.random.randn(4)

array([ 0.12696888, -0.27999651, -0.99939722,  0.12529449])

In [26]:
np.random.randn(4,4)

array([[ 0.64884511, -0.34226697,  0.19155172,  0.10245059],
       [-1.56639828,  0.92953343, -0.21219188, -2.28943898],
       [-1.62546129, -1.13514913,  1.82912043, -0.3190523 ],
       [ 0.90004707, -0.77228508, -0.15177343, -0.10438147]])

In [29]:
np.random.randint(1,10) #10 dönmez

4

In [31]:
np.random.randint(1,300,5)

array([298, 254,  86, 295, 184])

In [32]:
benimNumpyDizim=np.arange(30)

In [33]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
benimRandomDizim=np.random.randint(0,100,20)

In [40]:
benimRandomDizim

array([80,  6, 33, 92, 64, 94, 32, 19, 95, 22, 41, 16, 34,  5, 45, 36, 80,
       23, 86, 16])

# numpy dizi methodları

In [41]:
benimNumpyDizim.reshape(5,6)#dönüştür

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
benimNumpyDizim.max()

29

In [44]:
benimRandomDizim.max()

95

In [45]:
benimRandomDizim.min()

5

In [46]:
benimRandomDizim.argmax()#index

8

In [49]:
benimRandomDizim.argmin()

13

In [50]:
benimNumpyDizim.shape

(30,)

In [51]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [53]:
reshapeDizim.shape

(5, 6)