In [1]:
import numpy as np

In [2]:
benimDizim=np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8]=-5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi=np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
scilingDizisi=baskaDizi[4:9]

In [13]:
scilingDizisi

array([4, 5, 6, 7, 8])

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
type(scilingDizisi)

numpy.ndarray

In [16]:
scilingDizisi[:]=700

In [17]:
scilingDizisi

array([700, 700, 700, 700, 700])

In [18]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [19]:
ornekDizi=np.arange(0,24)

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasi=ornekDizi.copy()

In [22]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDiziKopyaSciling=ornekDiziKopyasi[3:6]

In [24]:
ornekDiziKopyaSciling[:]=800

In [25]:
ornekDiziKopyaSciling

array([800, 800, 800])

In [26]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix

In [29]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [30]:
benimMatrixDizim=np.array(benimListem)

In [31]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [32]:
benimMatrixDizim[0]

array([10, 20, 30])

In [33]:
benimMatrixDizim[1][2]

40

In [34]:
benimMatrixDizim[1,2]

40

In [36]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [38]:
benimMatrixDizim[2:,1:]

array([[50, 60]])

In [49]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [50]:
yeniMatrix=np.array(yeniListe)

In [51]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
yeniMatrix[[0,1,3]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

# operasyonlar

In [55]:
yeniBirDizi=np.random.randint(1,100,20)

In [56]:
yeniBirDizi

array([64, 84,  4, 52, 96, 46, 90, 81, 40,  2, 59,  2, 49, 79, 71, 97, 68,
       99, 77, 35])

In [57]:
yeniBirDizi>24

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [58]:
yeniBirDizi

array([64, 84,  4, 52, 96, 46, 90, 81, 40,  2, 59,  2, 49, 79, 71, 97, 68,
       99, 77, 35])

In [59]:
sonucDizisi=yeniBirDizi>24

In [60]:
sonucDizisi

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [61]:
yeniBirDizi

array([64, 84,  4, 52, 96, 46, 90, 81, 40,  2, 59,  2, 49, 79, 71, 97, 68,
       99, 77, 35])

In [63]:
yeniBirDizi[sonucDizisi] #sadece true olanları alır

array([64, 84, 52, 96, 46, 90, 81, 40, 59, 49, 79, 71, 97, 68, 99, 77, 35])

In [64]:
yeniBirDizi[yeniBirDizi>24]

array([64, 84, 52, 96, 46, 90, 81, 40, 59, 49, 79, 71, 97, 68, 99, 77, 35])

In [65]:
sonDizi=np.arange(0,24)

In [66]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [68]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [70]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [71]:
sonDizi/sonDizi

C:\Users\aslan\AppData\Local\Temp\ipykernel_1448\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [73]:
np.max(sonDizi)

23

In [75]:
np.min(sonDizi)

0